### ISSUE TITLE
Centrar imágenes

### ISSUE THREAD

**Issue by arkaitzgarro** [arkaitzgarro/libros-desarrollo#1]
Centrar las imágenes con respecto al contenido.

``` css
p > img {
  display: block;
  margin: 0 auto;
}
```
